<?php
    $data = new main();
    $fullForecastData = $data->getForecasts($_GET['placeCode']);
    $placeData = $fullForecastData->place;
    $forecastData = $fullForecastData->forecastTimestamps;
    $gridCount = 3;
?>

    <div class="card text-center">
        <div class="card-header">
            Selected forecasts
        </div>
        <div class="card-body">
            <h5 class="card-title"><?php echo $placeData->name; ?></h5>
            <iframe src="https://maps.google.com/maps?q=<?php echo $placeData->coordinates->latitude; ?>,<?php echo $placeData->coordinates->longitude; ?>&hl=en&z=6&amp;output=embed" width="100%" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>

        </div>
        <div class="card-footer text-muted">
            Prognoses for 7 days.
        </div>
    </div>
    <div class="container">
        <div class="row">

<?php
    foreach($forecastData as $forecast) {
        $gridCount++;

        if ($gridCount == 3) {
            $gridCount = 0;
            echo '
                </div>
                <div class="row">
            ';
        }

        echo '
            <div class="col-md">
                <div class="card text-center" style="width: 18rem;">
                    <div class="card-body header">
                        <h5 class="card-title">' . $forecast->forecastTimeUtc . '</h5>
                        </div>
                        <div class="card-body">
                        <p class="card-text"> Air tempreture: ' . $forecast->airTemperature . '</p>
                        <p class="card-text"> Wind speed: ' . $forecast->windSpeed . '</p>
                        <p class="card-text"> Wind gust: ' . $forecast->windGust . '</p>
                        <p class="card-text"> Wind direction: ' . $forecast->windDirection . '</p>
                        <p class="card-text"> Cloud cover: ' . $forecast->cloudCover . '</p>
                        <p class="card-text"> Sea level pressure: ' . $forecast->seaLevelPressure . '</p>
                        <p class="card-text"> Relative humidity: ' . $forecast->relativeHumidity . '</p>
                        <p class="card-text"> Total precipitation: ' . $forecast->totalPrecipitation . '</p>
                        <p class="card-text"> Condition code: ' . $forecast->conditionCode . '</p>
                    </div>
                </div>
            </div>
        ';
    }
    echo '
        </div>
    </div>
    ';
?>